# how to integrate the costumer application into buildroot
    - create your application directory inside buildroot package directory
        - mkdir package/userApps
    - register the application package in buildroot
        - nano package/Config.in
    - instruct buildroot to recognize your application packages
        - nano package/userApps/Config.in 
    - instruct buildroot to build and install the packages into target filesystem
        - nano package/userApps/userApps.mk
    - select the packages in menuconfig to be a listed in .config file
        - make menuconfig
    - build the image
        - make
    - note: if the application package has sub-directories further changes are nededed inside the Config.in and userApps.mk files